apiVersion: apps/v1
kind: Deployment
metadata:
  name: taller-microservice-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: talleresmicroservice
  template:
    metadata:
      labels:
        app: talleresmicroservice
    spec:
      containers:
      - name: talleres
        image: tallermicroservice.azurecr.io/amiltonr/tallermicroservice
        imagePullPolicy: Always
        ports:
        - containerPort: 80
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  name: taller-microservice-svc
spec:
  selector:
    app: talleresmicroservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
